name: intro_screen
description: A new Flutter package project.
version: 0.0.1
homepage: 

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^2.0.0
  extra_alignments: ^1.0.0+1
  flextras: ^0.0.2
  flutter_animate: ^1.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
